services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-php
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./vendor:/var/www/vendor
      - ./app:/var/www/app
      - ./core:/var/www/core
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: restaurant-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: district_lounge
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: restaurant-pma
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  db_data:
